---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  ports:
  - name: web
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    {{- include "selectorLabels" . | nindent 4 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "labels" . | nindent 8 }}
    spec:
      nodeSelector:
        kubernetes.io/hostname: {{ .Values.nodename }}
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: {{ .Values.claimname }}
      containers:
      - name: filebrowser
        image: filebrowser/filebrowser
        ports:
        - containerPort: 80
          name: web
          protocol: TCP
        volumeMounts:
        - name: "storage"
          mountPath: /srv
        securityContext:
          privileged: true
      initContainers:
      - name: increase-vm-max-map
        image: busybox
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      - name: increase-fd-ulimit
        image: busybox
        command: ["sh", "-c", "ulimit -n 65536"]
        securityContext:
          privileged: true
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "fullname" . }}-ingress
  labels:
    {{- include "labels" . | nindent 4 }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
    nginx.ingress.kubernetes.io/session-cookie-name: route
    nginx.ingress.kubernetes.io/configuration-snippet: |
      #client_max_body_size 100M;
      default_type  application/octet-stream;
      sendfile        on;
      #tcp_nopush     on;
      keepalive_timeout  1d;
      fastcgi_read_timeout 1d;
      #proxy_read_timeout 1d;
      #gzip  on;
spec:
  tls:
  - hosts:
    - {{ .Values.host }}
    secretName: {{ .Values.host }}-tls
  rules:
  - host: {{ .Values.host }}
    http:
      paths:
      - backend:
          serviceName: {{ .Chart.Name }}
          servicePort: 80
        path: /
